### ISSUE TITLE
Make chrome XPI :: details :: site access work with on premises GitHub enterprise

### ISSUE THREAD

**Issue by joeljensen** [ckeditor/github-writer#346] opened 2022-08-05 16:54 UTC
I work at UHG, we have 50,000 developers.  My team, which has 5 developers were looking at using this for editing GitHub pages.

I like the idea of your product, but it isn't usable with enterprise hosted GitHub.

I downloaded an earlier version years ago, and was able to modify it to work with github.optum.com, but the chrome configs and builds are no longer in the repo, and I don't have time to modify it.

It'd be nice if in chrome plugin :: details

Site access:
This extension can read and change your data on sites. You can control which sites the extension can access.
Automatically allow access on the following sites
https://github.com/*

-- was changed to --

https://github.com/*
https://github*

This would cover most enterprise installations.

The internal pages links would need to change as well, I perused the code and there are a few spots where GitHub.com was called out explicitly, perhaps a regex there as well?

I haven't looked at Firefox plugin details, or safari if your product supports that now.

**Comment by mateuszzagorski** [comment] 2022-08-16 13:47
Hi @joeljensen, Thank for the submission, and a detailed description.  
  
Can you please send us a anonymized enterprise url so that we know which cases specifically we should tackle here?  
In addition, I would be obliged if you could share a sample url for creating a new issue or pr (to compare the url paths)?

**Comment by mateuszzagorski** [comment] 2022-08-17 06:27
As this issue is a duplicate of ckeditor/github-writer#260, I would ask that we continue the conversation in there @joeljensen.

**Closed by mateuszzagorski** 2022-08-17 06:27 UTC
Labels: squad:green
