### ISSUE TITLE
Tooltips do not show up until the page is refreshed

### ISSUE THREAD

**Issue by dufipl** [ckeditor/github-writer#375] opened 2022-10-05 13:51 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Build GH Writer on `ghw/epic/388-version-3521-bump` branch 
2. Try to open a new issue. 
3. Hover toolbar buttons, if tooltips show up, go to the issue list and try to create the issue again.

### ✔️ Expected result

Tooltips show up regardless of the cache.

### ❌ Actual result

Tooltips do not show up until the page is refreshed 
![tooltips issue](https://user-images.githubusercontent.com/32898551/194076883-a8143d71-dc16-4fa6-ad83-0d67be283c54.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment] 2022-10-05 21:42
Interesting, this issue should be in case reproducible in vanilla CKE5 - let's investigate it further.

**Comment by Acrophost** [comment] 2022-10-06 09:41
More bugs most likely related to cache (occur when tooltips are not showing up):

In markdown (nostalgia) editing there is no preview or bottom bar for adding files from computer. Hard refresh/clearing cache fixes it just like tooltips 

![](https://user-images.githubusercontent.com/66953380/194280462-ed2794ef-834b-48ad-a3cd-32c1d8495c36.png)

**Comment by mateuszzagorski** [comment] 2022-10-06 10:07
Bottom bar is not visible because body does not have the `github-writer-loaded` class and so the CSS rules we have are causing it to have `display: none`. Not sure yet why that's happening - investigating.

**Comment by mateuszzagorski** [comment] 2022-10-06 14:44
Regarding the tooltips what I see is that inside the `ck-body-wrapper` we're missing a div with `ck ck-balloon-panel ck-balloon-panel_arrow_n ck-balloon-panel_with-arrow ck-tooltip` classes.  

In the recently added `tooltipManager` we have the `bodyViewCollection` that's set to `first( TooltipManager._editors.values() )` and because of that we're targeting the editor that's no longer visible but it is still available via the `TooltipManager._editors.values()`.    
  
So in my opinion we have to update the `ckeditor5-ui` plugin in order to fix the issue.  
  
You can replicate the similar behavior:  
\- use the `all-types` manual test  
\- destroy the ClassicEditor  
Without it tooltips will no longer be visible in all the other editors.

**Comment by Dumluregn** [comment] 2022-10-07 12:55
I agree with @mateuszzagorski 's conclusions. I'll report an upstream issue in CKE5 repo and once it's resolved, we should go back here to ensure it fixed Writer.

**Comment by Dumluregn** [comment] 2022-10-07 13:03
Reported in ckeditor/ckeditor5#12602.

**Comment by mlewand** [comment] 2022-10-10 08:09
Closing as an upstream issue.

**Comment by dufipl** [comment] 2022-10-24 12:43
@mlewand As the upstream issue is closed, I assume it should be fixed, but it's not, therefore I will reopen the issue.

Updating branch in reproduction steps to `ghw/epic/388-version-3521-bump`.

**Comment by mlewand** [comment] 2022-11-16 14:31
This should be fixed with #417.

**Closed by mlewand** 2022-11-16 14:31 UTC
Labels: bug, upstream, squad:green, regression
