### ISSUE TITLE
 With the current github layout, the original bar remains... and it is almost useless.

### ISSUE THREAD

**Issue by ShapeGroup** [ckeditor/github-writer#209] opened 2020-07-16 22:39 UTC
Maybe not really an issue ... With the current github layout, the original bar remains. I don't know where to start, however ... If I were you I would completely replace it with yours (which is really excellent) leaving if possible a very small "hide / show original bar" button in case something goes particularly wrong.  
Allow me to say this because the git bar becomes almost useless if you complete yours.  
  
Greate job.  
Good Works.

**Comment by fredck** [comment] 2020-07-17 09:08
Thanks for the feedback and for the nice words ;)

I'm a bit confused though when you say "the original bar remains". What do you mean by that? Maybe I see something different here. Maybe you're able to show what you mean with a screenshot?

**Comment by ShapeGroup** [comment] 2020-07-17 11:07
yes. I can.  
 

![](https://user-images.githubusercontent.com/22998552/87779996-11bef700-c82e-11ea-8dd8-3c53d717d2cb.jpg)

extra:  
I don't know if it's possible to add it but consider that it doesn't appear on the classics README.md but only on the wiki.  
in any case it is a holy hand for the wiki. When I found out I was happy hahaha

**Comment by fredck** [comment] 2020-07-17 12:36
Oh, that's totally clear now... and it is curious that you see the original GH toolbar. This is what I see:

![](https://user-images.githubusercontent.com/630060/87786547-636d7e80-c83a-11ea-9a79-a3ac810b1e10.png)

This means that there is something wrong which I'm not able to reproduce here, so we would have to investigate it at your side. These are the first things that come to my mind:

*   What's your browser name and version? What's the OS?
*   Does this happens when using "Create new page" as well?
*   Do you see any error in the browser console?

Thanks for the help!

**Comment by ShapeGroup** [comment] 2020-07-17 13:07
Currently: Windows 10;  
Firefox Developer 79.0b8 (64 bit);  
Deactiveted all other plugin of firefox: not is chenged;  
In all test, into console I have only this:  
http -> developer.mozilla.org/en-US/docs/Tools/Debugger/Source\_map\_errors?utm\_source=mozilla&utm\_medium=firefox-console-errors&utm\_campaign=default  
  
ps. If I can help you I'll try. I like this plugin.  :)

**Comment by fredck** [comment] 2020-07-17 13:36
Confirmed it with **Firefox** on mac as well. All good with Chrome.

That's good news and the first step to have this fixed soon. Thanks for the feedback, @ShapeGroup.

**Comment by fredck** [comment] 2020-08-19 14:21
I didn't identify the cause of it, but this seems to be fixed in current master.

**Closed** 2020-09-04 15:51 UTC
Labels: bug
